### ISSUE TITLE
Pro Feature Bug: Add Local Styles -> Use Local Styles

### ISSUE THREAD

**Issue by tenthstudio** [EightShapes/specs-plugin#100]
### Description

When the plugin is first set to Add Local Styles, and styles are generated, Token Studio's token ouput (as in literally the token name displayed) is defaulted to Inter and not connected to a style. The same applies for the style called "Marker Small". This style is currently unused in the output as the small marker should be the one referencing nodes, which text is defaulted to Inter like I said.

### Steps to reproduce

Add EightShapesSpecs Local Styles on a first Spec -> Change Value in Marker Small, the small marker is defaulted to Inter and therefore won't change. Same concept applies to token studio's token text when it comes out.

### Screenshot

<img width="1104" alt="image" src="https://github.com/EightShapes/specs-plugin/assets/118997518/1f1f2abd-52b4-48ce-ace3-bf135ae324f5">

<img width="763" alt="image" src="https://github.com/EightShapes/specs-plugin/assets/118997518/f4f933f5-7c44-444d-bb09-9966674bcbc9">

### Additional context

Love how the customization turned out! Doesn't help the bug but whatever.
Should further explainations be needed, DM on twitter /smndalena  or design@tenth.studio

### Defect log

null

**Comment by nathanacurtis** [comment]
@tenthstudio This is working as intended: the styles default to EightShapes Specs' default styles, and then you can (1) adjust the styles and then (2) run the plugin again to have it apply your chosen font family and other choices.
