### ISSUE TITLE
Submitted issue - lacks description

### ISSUE THREAD

**Issue by prithiv-kumar** [EightShapes/specs-plugin#104]
### Description

{Describe the bug in a sentence}

### Steps to reproduce

{Add steps to reproduce the error}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
@prithiv-kumar Thanks for submitting an issue indicating that you encountered an issue. However, I'll need details about what you encountered – what'd you run it on, what'd you see as a result, what'd you expect to see, etc. Even better, if you are willing, getting access to a view-only file (of even just the item, not the entire library or other things) will enable me to best inspect what's going on. Cheers.

**Comment by nathanacurtis** [comment]
Closing until more details are provided to enable triaging the issue.
