### ISSUE TITLE
in resize: Expected "width" to have value >= 0.01

### ISSUE THREAD

**Issue by sidcaplight** [EightShapes/specs-plugin#106]
### Description

Tried to run the plugin, plugin crashed

### Screenshot

<img width="1398" alt="Screenshot 2023-07-25 at 15 17 09" src="https://github.com/EightShapes/specs-plugin/assets/108527258/8da2055b-dfe4-455e-b653-0bfcc668ad63">

### Defect log

in resize: Expected "width" to have value >= 0.01

**Comment by nathanacurtis** [comment]
@sidcaplight Thanks for including the screenshot. Any chance I could get access to a view only file of the offending component for me to inspect and troublesheet? I don't need anything else...

**Comment by sidcaplight** [comment]
I've had to add this to private file for you https://www.figma.com/file/sNevQp1eTnodqIvSWf8k28/Untitled?type=design&node-id=0%3A3328&mode=design&t=Db7ZzfW0Ao52JXTw-1

**Comment by nathanacurtis** [comment]
![image](https://github.com/EightShapes/specs-plugin/assets/1165904/d20d5063-5ccd-411c-a69a-06914f41fb63)
Fixed for _this case_ using `.absoluteRenderBounds.width` in place of `.width`. 
Changed `markElement`'s access of `width`, `height` to `.absoluteRenderBounds.width`, `.absoluteRenderBounds.height` throughout
Need to run and compare with previous outputs across all test cases.

**Comment by nathanacurtis** [comment]
![Image](https://github.com/EightShapes/specs-plugin/assets/1165904/ce085986-74e0-46b9-b70f-a6952383f525)


Confirmed fixed in production. Don't forget to reboot Figma first so that you reload a fresh plugin before trying again.
