### ISSUE TITLE
in remove: The node with id "2519:9173" does not exist

### ISSUE THREAD

**Issue by Praneeth-Pike** [EightShapes/specs-plugin#109]
### Description

Plugin Encountered an error

### Steps to reproduce

Select a component with frames having min-width and max-width. Generate specs and there's an error

### Screenshot

![CleanShot 2023-08-02 at 16 26 56@2x](https://github.com/EightShapes/specs-plugin/assets/9357550/f33bed24-abd5-4f27-96cf-64a3f66ebe8a)

### Additional context

{Add any other context about the problem here}

### Defect log

in remove: The node with id "2519:9173" does not exist

**Comment by nathanacurtis** [comment]
@Praneeth-Pike thanks for submitting! Would it be possible to get access to the frame that produced the result?

**Comment by nathanacurtis** [comment]
@Praneeth-Pike Any chance you could provide a sample to inspect? Without that, I'm not confident I'll be able to isolate the defect.

**Comment by nathanacurtis** [comment]
Closing due to lack of details
