### ISSUE TITLE
FIGMA Crashed 

### ISSUE THREAD

**Issue by robertegomes** [EightShapes/specs-plugin#112]
### Description

{Describe the bug in a sentence}

### Steps to reproduce

{Add steps to reproduce the error}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
@robertegomes Thanks for your submission. Is there anything more you can report about the steps to reproduce the crash? What action was being performed on what object? Without more details about the incident, I won't be able to troubleshoot anything.
