### ISSUE TITLE
Design token not documented since beta started

### ISSUE THREAD

**Issue by Product-UX** [EightShapes/specs-plugin#115]
### Description
Since the start of the Columns beta, I am not able to document properly the design token. The blocks present the artwork but none of the token specs are available. 

{Describe the bug in a sentence}
Design token not documented 

### Steps to reproduce
- Select the component in a page where Tokens and variable are defined. (I have also tried with old components that were properly working in the past)
- Open Eightshapes specs plugin
- settings
Anatomy
List beside artwork
Properties on
modes off
Layout both on
Formatting 
use local styles
1 column
Token studio
Display raw value on

{Add steps to reproduce the error}

### Screenshot
<img width="1365" alt="Screenshot 2023-09-19 at 10 09 46" src="https://github.com/EightShapes/specs-plugin/assets/91541841/c7de8c46-05df-4c1f-b719-cffdba06240b">

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
@Product-UX Seeing the issue added and closed: can you confirm this is not an issue? In general, the columns feature should have no impact on detection and display of attributes across spec sections, so this would be a pretty unexpected development.

**Comment by Product-UX** [comment]
Hi Nathan,
  
​
  
​It was a mistake from my side. The information shows on nested components
  
​
  
​Sorry again for pressing submit too soon :(
  
​
  
​Patrick

**Comment by nathanacurtis** [comment]
@Product-UX  No problem. Glad you resolved your challenge :)
