### ISSUE TITLE
I can't use the plugin, it crashes the file

### ISSUE THREAD

**Issue by trgm** [EightShapes/specs-plugin#117]
### Description

{Describe the bug in a sentence}

### Steps to reproduce

{Add steps to reproduce the error}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
I am sorry to hear that. Can you provide any details around what action you were taking preceding the crash? I have noticed instability when copying a frame as PNG (CMD SHIFT C) when the plugin is open, for example, which is unrelated to the plugin but crashes it nonetheless.

**Comment by trgm** [comment]
When I open up figma > select any component > click eightshapes > create spec > crash

I quite literally cannot used eight shapes to spec anything without it crashing the file, even if i move the component to a brand new file and try it, it crashes.

**Comment by trgm** [comment]
Are you also saying me using the copy-paste is causing the plugin to crash?

**Comment by nathanacurtis** [comment]
@trgm I've not had other users identify something this direct and simple: open plugin, select item, click "Create Spec", crash. 

Is there any way you could record a screen recording video and/or share the selected item(s) in a view-only Figma file? You could post that here or, more privately, direct message me in the [EightShapes Spec Slack](https://join.slack.com/t/eightshapes-specs/shared_invite/zt-1w4k19pj7-viPHKW8045zak64u~lH4yA).

Regarding the "Copy as PNG", the steps I use to reproduce that are:
1. Open plugin
2. Select any item on canvas
3. Copy to PNG
-> crashes plugin. It's odd, that command has nothing to do with the plugin.

**Comment by nathanacurtis** [comment]
Pending any further input, closing the issue.
