### ISSUE TITLE
Anatomy format issue

### ISSUE THREAD

**Issue by wirrap** [EightShapes/specs-plugin#118]
### Anatomy format issue

Hey, a couple of days ago there was a feature to try the anatomy format toggle (in the free version), I tried "Table below artwork" a couple of times but usually I use "List beside artwork". Now the toggle is gone (I assume it is in the paid version only), but the plugin keeps generating the anatomy with the "Table below artwork" layout, and I'm not able to switch it back to "List beside artwork".
This issue is reproduced only in one of my libraries, while in other files it works fine as usual. Can the plugin settings be reset to default in a particular file?

**Comment by nathanacurtis** [comment]
@wirrap Good catch! Sorry I missed that. I've published an update that sets the anatomy format setting to vertical list for users that haven't subscribed to the upgraded features. To take advantage of this update, you may need to restart Figma and restart the plugin from there. Please let me know if you continue having issues with the setting.

Thanks,
Nathan

**Comment by wirrap** [comment]
@nathanacurtis all works now! Thank you a lot for such a quick reaction!
