### ISSUE TITLE
Hug/Fill Parent/Child Pair not rendering layout specs correctly

### ISSUE THREAD

**Issue by l1k3t3rr13r** [EightShapes/specs-plugin#119]
### Description

When I create the specs the layout and padding and the annotations are not corresponding with the frames correctly

### Steps to reproduce

I selected the frames and created the specs as normal and everything renders but it's all in the wrong place. Here is a copy of the file: https://www.figma.com/file/mZl6yOgCcXTs7Tta8J2UPZ/Untitled?type=design&node-id=0%3A1&mode=design&t=BqGEzscxYIytjWnU-1

### Screenshot
![Screenshot 2023-09-29 at 12 32 06](https://github.com/EightShapes/specs-plugin/assets/134517791/27923f7c-f383-452f-9f21-3d95a98ebff3)
![Screenshot 2023-09-29 at 12 32 52](https://github.com/EightShapes/specs-plugin/assets/134517791/349ff46e-bd39-4840-9403-88270f515e11)
![Screenshot 2023-09-29 at 12 32 14](https://github.com/EightShapes/specs-plugin/assets/134517791/012f1300-1a7f-4236-aba1-29f9a4e2cf20)

### Additional context

I have tried restarting and updating Figma, removing the plug in from my saved area, and have tried creating a new Figma file but having the same issue

### Defect log

{Copy the message from the browser/Figma console, if relevant}

Thanks!

**Comment by nathanacurtis** [comment]
Reviewed page layout, confirmed as a defect.

## Notes

In investigating the narrowest page layout:

1. The plugin isn't formatting `Artwork` width correctly. Investigate the relationship of `Hug` horizontal resizing and default `Artwork` width in 1 column layouts.
2. The `Free Emails` section is impacting computations of layer height across all `Artwork` frames. The second child layer `Emails` is interpreted as 20px when it should be 482px.

![image](https://github.com/EightShapes/specs-plugin/assets/1165904/80e87adc-2895-4a41-b6d2-f403c7ef6f98)

**Comment by nathanacurtis** [comment]
Further investigation indicates that the interaction between the `Carousel` layer (vertical resizing `Hug`) and it's children items (vertical resizing `Fill`) is resulting in odd behaviors. Typically, having `Hug` contain `Fill`s can cause unpredictable results (in Figma in general, not the plugin output specifically).

While I will continue investigating the issue, changing `Carousel`'s vertical resizing to `Fixed` for the purposes of at least the narrowest layout results in correct specs.
![image](https://github.com/EightShapes/specs-plugin/assets/1165904/599a1fd4-18aa-4bf2-9051-313a21beaa5a)

**Comment by l1k3t3rr13r** [comment]
Great thank you Nathan, I will try this

**Comment by nathanacurtis** [comment]
While the Hug/Fill issue remains, the just-released plugin Version 35 has fixed for the improper display of Layout specs in 1 column format.
