### ISSUE TITLE
Two way displays across Props

### ISSUE THREAD

**Issue by austinstudio** [EightShapes/specs-plugin#128]
When building a spec, the plugin only documents the first variant for each mode.  We have a component with 7 variants and when we create the spec, it documents only the first variant.  We need the colors and design for all variants.

**Comment by nathanacurtis** [comment]
@austinstudio Thanks for your interest!

The **Properties** setting iterates through all options of each variant property, so I'm unsure what you are describing is missing relative to what the plugin already does.

I will say that the plugin doesn't iterate to compare every single variant, but only cycles through the available options per variant property. So, if you have two properties with 3 options each, you'll get two subsections of 3 exhibits each in the Properties section rather than 3x3=9 total exhibits. The latter is what I refer to as #21 Compound Properties, an open ticket I'd really love to tackle but expect it to be quite complicated and expensive to build in a useful and fault-tolerant way.  

Could you give a practical example, or even take a screenshot of your component set (the variants within the dashed component set boundary) and explain what you'd want to see relative to what you actually see?

**Comment by austinstudio** [comment]
> @austinstudio Thanks for your interest!
> 
> The **Properties** setting iterates through all options of each variant property, so I'm unsure what you are describing is missing relative to what the plugin already does.
> 
> I will say that the plugin doesn't iterate to compare every single variant, but only cycles through the available options per variant property. So, if you have two properties with 3 options each, you'll get two subsections of 3 exhibits each in the Properties section rather than 3x3=9 total exhibits. The latter is what I refer to as #21 Compound Properties, an open ticket I'd really love to tackle but expect it to be quite complicated and expensive to build in a useful and fault-tolerant way.
> 
> Could you give a practical example, or even take a screenshot of your component set (the variants within the dashed component set boundary) and explain what you'd want to see relative to what you actually see?

Yes, take a look at this component (https://www.figma.com/community/file/1315081439055940966).  It has 7 different variants.  Each of those 7 variants have a light mode, dark mode, and wireframe mode.  When I run the plugin on it, it only creates the Modes for the first variant and doesn't do any of the colors or visuals for the other variants like it does for the Properties portion of the spec. so we cannot see what the other variants look like in each of the modes.  It seems like it is just missing a loop in the code somewhere under the modes section.

**Comment by nathanacurtis** [comment]
If you are referring to a literal trio of modes based on a Figma variable collection, that is supported: by upgrading from the free to subscribed version to unlock the [Modes](https://github.com/EightShapes/specs-plugin/blob/main/docs/pro-features/modes.md) feature (and [Variables](https://github.com/EightShapes/specs-plugin/blob/main/docs/pro-features/figma-variables.md) in general).

**Comment by austinstudio** [comment]
I have the paid version.  The Modes section doesn't iterate through the modes and variants, it only documents the first variant of the component for each mode.  So for us, the first variant is green... in dark mode it is white.  The second variant is dark yellow and light yellow in dark mode.  When I run the plugin, it only documents the mode for the green one and doesn't display anything for the yellow one.  If I were a developer I wouldn't know what the other variants look like in each of the modes.

**Comment by austinstudio** [comment]
Here is a screenshot.  On the left is what the plugin creates.  It only is taking the first variant of the three blocks on the right.  On the right are all of the variants in all three modes.  The plugin should iterate through all of the items on the right for the modes or else the dark and low-fi modes don't get documented at all and it defeats the point of using the plugin.
<img width="983" alt="Screen Shot 2024-01-11 at 11 25 09 PM" src="https://github.com/EightShapes/specs-plugin/assets/1907053/3ebeb9c0-2e76-4611-bc45-e4a6168b8b6d">

**Comment by nathanacurtis** [comment]
@austinstudio Ah, that's helpful, and confirms what I expected: you'd like to see "compound" displays, albeit combining both a prop and a mode (earlier, before variables, it was just combine two props). You can produce that manually today, fwiw, by running the plugin seven times and assembling the results. But ideally, the plugin would feature an option for that, enabling you to select which two props/modes to compound.

**Comment by nathanacurtis** [comment]
@austinstudio You can select components (as opposed to "the entire component set") and run the plugin against each. So, you'd successive run the plugin on each "light mode" variant, such as teal then blue then green then red then..., assuming each of those is distinguished by a component property, not mode.

**Comment by nathanacurtis** [comment]
@austinstudio I've been wanting to do this for a long time. It's not difficult to produce the artwork of the exhibits by iterating through the options. But the _differencing_ (to compare every attribute for every type of attribute (hardcoded? tokens studio? variable? style?) of every layer of every variant across ... another variant or mode)? That's the secret sauce, and involves considerable refactoring and expansion of the plugin's engine. I definitely get the pain you are feeling, I'm feeling it too. It's just ... complicated, far more than what it appears.

**Comment by austinstudio** [comment]
@nathanacurtis I figured it was just a few more loops in the code.

**Comment by nathanacurtis** [comment]
@austinstudio The concept we're discussing is very similar to the concept of a "Two way" analysis in statistics. Naming and describing this feature is challenging. Given that the user would have to identify the two dimension (in your example, tokens and type), how do you react to this option in the UI?
![image](https://github.com/EightShapes/specs-plugin/assets/1165904/6122bf5f-3578-4434-9160-c4e82515aea4)

**Comment by austinstudio** [comment]
> @austinstudio The concept we're discussing is very similar to the concept of a "Two way" analysis in statistics. Naming and describing this feature is challenging. Given that the user would have to identify the two dimension (in your example, tokens and type), how do you react to this option in the UI? ![image](https://private-user-images.githubusercontent.com/1165904/296512670-6122bf5f-3578-4434-9160-c4e82515aea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NDEyNTksIm5iZiI6MTcwNTQ0MDk1OSwicGF0aCI6Ii8xMTY1OTA0LzI5NjUxMjY3MC02MTIyYmY1Zi0zNTc4LTQ0MzQtOTE2MC1jNGU4MjUxNWFlYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMjEzNTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ0N2MxODNlOTVmOTkyYWE4NDRhOTMxNzQ3Y2JhMzFiNzE3MzIzYTMyMTZkYzljYmRmZWYwZjNmMzA0Yjk1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XvGZl_lZWG-_HhFeU8dLEAaC0RrRysQWrpN-RTmZLhA)

-------

Looks like a good first idea.  Does this new "Two-Way" show up when you select yes to the "Modes" question.  For now, the Modes option says "Difference visual attributes by mode" which seems to encompass all visual attributes across the modes.  The concept would work, but wouldn't this make the dialog really large if there were a lot of variants?  Could it assume that if you say yes, you want all of the variants to be documented?  If that works, then maybe it could be enhanced to include an option to toggle each one on and off if needed?

**Comment by nathanacurtis** [comment]
@austinstudio 
I'd imagined this scenario. Imagine an Alert component has the following variant properties and detected modes:
* `severity` variant property (info, success, warning, error, basic)
* `variant` variant property (filled, outlined, standard)
* `density` mode (compact, cozy, comfortable)
* `color` mode (light, dark, high-contrast, wireframe)
* `size` mode (small, medium, large)

Then, the specs plugin would show:
* Properties toggle
* Modes toggle
* Two-way toggle, with...
* Prop/Mode 1 = `severity` (Property) (which could be changed to `variant`, `density`, `color` or `size`)
* Prop/Mode 2 = `variant` (Property) (which could be changed to `density`, `color`, or `size`)

Want to run different "Two Way" combos? Run the plugin twice. I cannot imagine starting to run "all the possible two-way combinations", because that would take forever to run and blow up the displayed specification.

**Comment by austinstudio** [comment]
Yea, it can work.  Sounds like a decent design.

**Comment by nathanacurtis** [comment]
Progress on compound displays, now as working branch. Testing and UI still pending.

![image](https://github.com/EightShapes/specs-plugin/assets/1165904/d4b3e6a1-9026-4bb5-aced-ae567b0d81fa)

**Comment by nathanacurtis** [comment]
@austinstudio The Two Way Comparisons feature is now launched for subscribers. Hope it helps, and let me know if you have any other feedback.
