### ISSUE TITLE
Retrieve variant and component descriptions when running the pluggin

### ISSUE THREAD

**Issue by blv-Adrian-Lombera** [EightShapes/specs-plugin#134]
Hi! Eightshapes plugins would facilitate documentation if it could retrieve the component and variants descriptions. That would allow to centralise all creation and documentatory efforts on the master component and would help a lot on discovering and reading documentation. I attach captures.

1.
![Screenshot 2024-02-12 at 12 33 10](https://github.com/EightShapes/specs-plugin/assets/57437179/a1f3571a-5065-4a48-80d7-e5d8f6f22147)
2.
![Screenshot 2024-02-12 at 12 36 17](https://github.com/EightShapes/specs-plugin/assets/57437179/31817e16-71e1-4214-a2f4-62a592b43096)

**Comment by nathanacurtis** [comment]
Hi @blv-Adrian-Lombera, thanks for your interest in the plugin!

Ah, yes, the descriptions. This has long been a request (see #5 ), but is complicated by the rich text formatting of the field. I'm not sure if I'm up to the task of converting that rich text into Figma frames, and it'd likely be very error prone. It's also been a rarer request relative to other items in the backlog too. I'll keep in mind :)
