### ISSUE TITLE
When running a plugin for a component with a large number of variables (32), the plugin generates an error

### ISSUE THREAD

**Issue by sashu-sashu** [EightShapes/specs-plugin#144]
### Description

{Describe the bug in a sentence}

### Steps to reproduce

{Add steps to reproduce the error}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
@sashu-sashu Thanks for submitting the defect. Certainly, complicated components can take a long time to process, and it's possible to make a component that cannot be processed before the browser throws a warning. 

However, I'd want to learn more about the error and the specifics of the component you've created.
– Would it be possible for you to share the component in a view-only file for me to reproduce and troubleshoot?
– What was the text of the error you observed?

**Comment by sashu-sashu** [comment]
Thank you for the response!
-Unfortunately we can not share the component
-The text of the error is below
![Screenshot 2024-02-22 at 13 40 00](https://github.com/EightShapes/specs-plugin/assets/105430184/8620d83e-6a14-4061-a0ce-0bcb73139cfe)

**Comment by nathanacurtis** [comment]
@sashu-sashu Unfortunately, without more information: screenshot of the component or an ability to inspect the layers/nodes that make up what the plugin inspected, the error `cannot read property value` is too vague for me to diagnose anything. I'll have to close the issue if I don't otherwise hear from you.
