### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Popovandsons2024** [EightShapes/specs-plugin#148]
### Description

{Describe the bug in a sentence}

### Steps to reproduce

{Add steps to reproduce the error}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by Popovandsons2024** [comment]
go

**Comment by nathanacurtis** [comment]
@Popovandsons2024 I'll leave this open momentarily, but will close shortly otherwise if useful content isn't added. Cheers :)
