### ISSUE TITLE
Error encountered… may be font related? 

### ISSUE THREAD

**Issue by jbrownvirtuoso** [EightShapes/specs-plugin#158]
### Description

{Describe the bug in a sentence}

### Steps to reproduce

{Add steps to reproduce the error}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
@jbrownvirtuoso Yes, there are font defects that crop up from time to time, but not recently. I'll need considerably more details – screenshot? steps to reproduce? ideally, sample for me to troubleshoot shared in a few only file? – for me to be able to act on it, though.

Looking forward to seeing what you have.

**Comment by nathanacurtis** [comment]
@jbrownvirtuoso I'm closing this issue as unresolved. Please let me know if you have further information I can review, and I'll reopen it. Cheers.
