### ISSUE TITLE
Can't purchase plug in

### ISSUE THREAD

**Issue by Irvro** [EightShapes/specs-plugin#167]
### My payment details are correct, I add my address and the Complete Purchase Button keeps showing disabled.

I understand that VAT it's opcional, so what's stopping me from completing the purchase?

Complete purchase button disabled.

### Steps to reproduce

Add payment details, add address, I don't add the VAT as is optional and I don't have one.
### Screenshot
<img width="359" alt="Captura de Pantalla 2024-06-21 a la(s) 11 41 17" src="https://github.com/EightShapes/specs-plugin/assets/76503152/b81fd071-3305-482a-be6f-c55b30c500d1">

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
@Irvro That's strange. Unfortunately, that's a dialog managed by the Figma payment platform, not by my plugin. To inquire about how that could be fixed, you'd need to contact support@figma.com. If you contact that, I'd value being cc'ed to understand how to help people like you resolve this issue. Sorry I can't be of further help.

**Comment by Irvro** [comment]
Solved, it was an issue from my side, for some reason G-Pay (google) doesn't work properly, so I had to enter my card details manually. The purchase was successful. Sorry for the false alarm, thanks for the quick answer!
