### ISSUE TITLE
Fixing random placement of generated specifications

### ISSUE THREAD

**Issue by burlachkaa** [EightShapes/specs-plugin#178]
**Is your feature request related to a problem? Please describe.**
Unfortunately ES just randomly inserts generated specs without asking me where I'd like it to be inserted. I often work with quite large files, and it's inconvenient to search for the generated specifications in all my layouts. Sometimes, Eight Shapes inserts the specifications directly into my layout, which is especially disappointing (

**Describe the solution you'd like**
Have an option to choose where the Eight shapes will insert the generated specifications. Would be nice to have "Paste here" button or something like that.

**Describe alternatives you've considered**

**Additional context**
This is the way how Figma allows paste different content. Would be great to have something similar.
![Uploading Screenshot 2024-08-23 at 16.40.56.png…]()

PS. I love your product and appreciate all the functionality you've already done, thank you for that :)

**Comment by burlachkaa** [comment]
The problem is that sometimes we create specifications for components several times, and there can be several specifications on the one page. And new specifications can be inserted anywhere. Having an option to manage where the Eight shapes will insert the generated specifications would help our team a lot

**Comment by nathanacurtis** [comment]
@burlachkaa Oh, yes, the plugin won't deduplicate specs that have been already produced. There is a #81 issue that's longstanding that I've been considering working on.

However, new specs aren't inserted anywhere; instead, they are appended to the end (right most) of the set. In cases where you have selected "Spec nested components", they are added in the order they are detected as the plugin crawls the selected items. Can you be more specific about what you mean by "inserted anywhere?"

**Comment by nathanacurtis** [comment]
Closing due to no additional content added to diagnose the issue. If more information is provided, I'd be happy to help troubleshoot.
