### ISSUE TITLE
Variable Does Not Exist

### ISSUE THREAD

**Issue by willy3087** [EightShapes/specs-plugin#182]
![CleanShot 2024-09-12 at 10 23 59@2x](https://github.com/user-attachments/assets/299dcdda-216e-446b-bfe4-2bae4b3a1351)

### Description

{Describe the bug in a sentence}

### Steps to reproduce

{Add steps to reproduce the error}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
@willy3087 Any chance I could more information and / or access to the example triggering this so that I can troubleshoot?

**Comment by nathanacurtis** [comment]
@willy3087 Would it be possible for you to provide more details and/or access to a file that contains the triggering frame/component? If not, I'll need to close this issue as unresolvable.
Thanks. :)

**Comment by nathanacurtis** [comment]
@willy3087 Would you be able to provide greater clarification and/or file access for troubleshooting? Otherwise, I'll close this ticket as unresolved. Thanks for your help :)
