### ISSUE TITLE
getSharedPluginData: Expected "key" to have type string but got undefined instead

### ISSUE THREAD

**Issue by josemarques** [EightShapes/specs-plugin#183]
### Description

Trying to run the plugin on simple component with only a shadow stile and s rectangular shape inside and gettings this error:

<img width="337" alt="Screenshot 2024-09-13 at 16 30 56" src="https://github.com/user-attachments/assets/025ce3c3-066b-4775-92be-0d3f54f2fc94">

**Comment by nathanacurtis** [comment]
@josemarques Can you share a file with the offending selected item? I would hope to diagnose and fix this fairly quickly

**Comment by nathanacurtis** [comment]
@josemarques Would it be possible for you to provide more details and/or access to a file that contains the triggering frame/component? If not, I'll need to close this issue as unresolvable.
Thanks :)

**Comment by nathanacurtis** [comment]
Added checks to ensure Tokens Studio key is defined before evaluating Shared Data.
