### ISSUE TITLE
Add component set and variant description to the specs

### ISSUE THREAD

**Issue by nunofs8** [EightShapes/specs-plugin#184]
There is no way to add extra context to a component. This creates an unnecessary layer of extra work to update the specs after generating them and also creates a problem when an update is needed and a new specs is generated.

**Describe the solution you'd like**
I would like to include the figma component set and variant description to the specs.

**Describe alternatives you've considered**
Nothing that can be done automatically. Currently we need to manually add descriptions for variants.

**Comment by nathanacurtis** [comment]
Hi @nunofs8, thanks for your request :)

This capability is already partially described in a long standing feature request #5. I've put work into this in the past, and ran into complications, particularly with formatting (both unformatted and rich text versions of descriptions) within Figma frames. It got way more complicated than expected. Nevertheless, I'll put some more thought into this. 

As a result, I'm going to close this issue in favor of #5, and add the "Variant differencing" to that issue.
