### ISSUE TITLE
Can't run the plugin and also found an error

### ISSUE THREAD

**Issue by daviddesignsystems** [EightShapes/specs-plugin#185]
### The plugin is not working for me. Please help

{Describe the bug in a sentence}

### I just ran it on some master components. The plugin crashes the page and I also got the following error:
The plugin encountered an error cannot read property 'defaultValue' of undefined
To report this error to the plugin author, submit an issue, include the message above and (if you are willing) include a link to a view-only file with the items) you selected so the plugin author can troubleshoot.

**Comment by nathanacurtis** [comment]
@daviddesignsystems That's an error I've not encountered before. Any chance you can provide access to (at least) view-only Figma assets for me to troubleshoot? Often users will paste the offending frame/instance/component into a separate file to minimize how much they need to share.

**Comment by nathanacurtis** [comment]
@daviddesignsystems Would you be able to provide greater clarification and/or file access for troubleshooting? Otherwise, I'll close this ticket as unresolved. Thanks for your help :)
