### ISSUE TITLE
Use code syntax for variable names

### ISSUE THREAD

**Issue by chandlersimon** [EightShapes/specs-plugin#188]
**Problem**
Currently the specs show the correct variable being used, however it would be nice if there was an option to use the code syntax applied to the respective variable. Our naming scheme for variables in Figma differs slightly to dev so we have given every variable the correct code syntax.

**Possible solution**
Add a checkbox in Settings > Custom formatting that says "Variable Naming"  then provide a dropdown with the options "Default, Syntax: Web, Syntax: Android, Syntax: iOS"

**Screenshots**
![Screenshot 2024-11-13 at 3 53 59 PM](https://github.com/user-attachments/assets/88dcf1e2-6d57-4ef1-af83-fbb1bec64cf3)

**Comment by nathanacurtis** [comment]
@chandlersimon Interesting. Given that [code syntax](https://www.figma.com/plugin-docs/api/Variable/#codesyntax) is supported, would you expect that ...

If the code syntax setting is set to a platform and that platform is available in `codeSyntax`, show that string. Otherwise, show the variable default name?

**Comment by chandlersimon** [comment]
Yes, exactly. So maybe in Settings > Custom formatting having a dropdown that says "Use Figma code syntax naming if available". And the dropdown options would be "Web, Android, iOS".

**Comment by nathanacurtis** [comment]
Also, would you expect the variable collection name to no longer appear, showing JUST the `codeSyntax` value? Or would you expect to see **{Variable collection name}** {codeSyntax value}?

**Comment by chandlersimon** [comment]
I personally would expect no "{Variable collection name}" because our dev's don't organize variables in groups like that. I assume this is the more common method too. Thanks for the fast replies.

**Comment by nathanacurtis** [comment]
Your welcome, it's published as a new setting. Be sure to restart Figma app or the browser from the ground up to see the change, and let me know how it goes. :)

**Comment by chandlersimon** [comment]
Amazing, thank you! It seems to be working for Web, and Android but not for iOS. Example test here:
![Screenshot 2024-11-13 at 10 00 15 PM](https://github.com/user-attachments/assets/3713d8c8-205d-48d0-9301-92b4a8d3bdd4)
![Screenshot 2024-11-13 at 9 59 10 PM](https://github.com/user-attachments/assets/f488971d-7464-4756-9a62-4e00b3070a5b)

**Comment by nathanacurtis** [comment]
Pesky `iOS` instead of `IOS`. The plugin API's off-convention lowercasing of `i` got to me in one place. Sigh, should be fixed now.

**Comment by chandlersimon** [comment]
Working great now, thank you!
