### ISSUE TITLE
Unloaded Fonts

### ISSUE THREAD

**Issue by emm-yu** [EightShapes/specs-plugin#189]
### Problem

Plugin was working, now giving an error. 
<img width="300" alt="image" src="https://github.com/user-attachments/assets/68ba0b26-ce0e-4780-9a03-8dd69961d277">

### Source file to troubleshoot

Access to the frame/instance(s) that trigger the defect are essential for the plugin maker to troubleshoot the issue. A screenshot of the vague Figma error message is not enough. If possible, provide access to a view-only Figma file – even with JUST the frame or instance in it – by pasting the shared link below or DM'ing Nathan privately in the Specs Plugin Slack (https://join.slack.com/t/eightshapes-specs/shared_invite/zt-1w4k19pj7-viPHKW8045zak64u~lH4yA).

[{Paste link here}](https://www.figma.com/design/v5yoZqLKeLGTo9giU8myuT/(Web)-Design-Systems-2.0?node-id=60289-74966&t=JR3Xr6C28q3jZHSs-4)

### Screenshots

If possible, paste screenshots from your clipboard, including ideally:
* Current Specs plugin UI settings (if a defect is currently displayed, restart the plugin and screenshot those settings)
* Frame(s)/instance(s) on which the plugin is being run
* Output the plugin produced
* Bug(s) displayed in the plugin's UI

<img width="320" alt="image" src="https://github.com/user-attachments/assets/ed11fda3-d099-4f94-86b6-4153f1da1a8d">
<img width="320" alt="image" src="https://github.com/user-attachments/assets/2d6fd79d-9058-4804-b716-23298540489b">

### Additional context

I am using Avenir in the custom formatting.

**Comment by nathanacurtis** [comment]
Any chance you could...
1. Share a view-only file for me to troubleshoot?
2. If not, paste a screenshot of your EightShapes Specs variable collection for typography?

This is possibly something I can fix but I'd need access to the file to understand what's going on.

**Comment by nathanacurtis** [comment]
@emm-yu Still hoping to hear from you with the possibility that I could troubleshoot the example from a view-only file that you'd provide. If I don't hear from you by next Monday December 9th, I'll need to close this ticket due to nonresponse.

**Comment by nathanacurtis** [comment]
Closing due to nonresponse and inability to troubleshoot.
