### ISSUE TITLE
Bug Properties are not being generated

### ISSUE THREAD

**Issue by saumyakb** [EightShapes/specs-plugin#73]
### Description

Properties are not being generated

### Steps to reproduce

select component> run the plugin

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}
![image](https://github.com/EightShapes/specs-plugin/assets/5933708/93424fe9-9d02-404b-9cef-8655565a7e1c)

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
Per @saumyakb comment in Slack:
> Hey its an issue with my components its working fine for other components on my file its just this one thats causing an issue
