### ISSUE TITLE
Alignment: "space evenly" instead of "space-between"

### ISSUE THREAD

**Issue by igapeka** [EightShapes/specs-plugin#82]
I've noticed that the plugin put "spaced evenly" to the Alignment property of container while its actual value is "space-between". Space-evenly is another value of alignment and children behave differently within a parent with space-evenly assigned. This could potentially cause misunderstanding.

![Frame 4](https://github.com/EightShapes/specs-plugin/assets/98242356/028fcd4d-ce23-4550-8e63-5c0056884e76)

**Comment by nathanacurtis** [comment]
@igapeka Good point! I was unaware of `space-evenly` in the CSS implementation of `justify-content`. My use of `, space evenly` was a well intentioned but ultimately poor choice of an implementation-agnostic attribute value.

In reviewing `justify-content` [docs on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content), could you imagine an implementation-agnostic summary of something like `Distributed evenly, items flush with ends`? Or, would you prefer it simply say "Space between", even though that's less descriptive and potentially too attached to Figma's UI choice?

**Comment by igapeka** [comment]
Emm... "spaced equally"?)

**Comment by nathanacurtis** [comment]
I can dig that. Will prioritize this simple fix for the next release. Thanks so much for submitting!
