### ISSUE TITLE
Error: "Invoke callback with invalid ID" (Figma Payments API issue)

### ISSUE THREAD

**Issue by paquesgustavo** [EightShapes/specs-plugin#83]
### Description

I'm trying to create a spec but every time I run the plugin I get an error message.

### Steps to reproduce

Run plugin

### Screenshot

![Screen Shot 2023-06-01 at 16 59 12](https://github.com/EightShapes/specs-plugin/assets/41834759/04022f98-aff0-4b19-874a-9fa2021676dc)

### Additional context

{Add any other context about the problem here}

### Defect log

in <unknown>: Attempted to invoke callback with invalid id -32766

**Comment by burasuk** [comment]
i've the same problem

**Comment by nathanacurtis** [comment]
According to Figma, this was due to an issue with the Figma payments API, and they issued a fix for this issue later last week. @burasuk, can you confirm you are getting that same exact error message? If so, I'll communicate to Figma that the issue may not be resolved.

**Comment by nathanacurtis** [comment]
@paquesgustavo Are you still encountering this error, even after restarting Figma (and thus, reloading both Figma and the plugin)? If I don't hear from you soon, I'll go ahead and close the issue. Thanks!

**Comment by burasuk** [comment]
Everything is working now.
