### ISSUE TITLE
Component manifest

### ISSUE THREAD

**Issue by twjeffery** [EightShapes/specs-plugin#88]
**Is your feature request related to a problem? Please describe.**
I'm a designer, and I use a design system in Figma that has equivalent components available from the design system in code. I want to improve my handoff with my developers, so that they can read this spec of the design intent and see all the available components highlighted, in the same way that they can see the design tokens.

**Describe the solution you'd like**
Highlight Figma components used, like it is currently with design tokens. We have parallel components available in development, so I want to make it super easy to see what components and tokens are used, for a developer to easily get what they need to build in code.

**Comment by twjeffery** [comment]
Yea exactly! 

That totally makes sense. Maybe this is too niche then, I can see how this might make more sense to do manually referencing coded resources. As we can currently add a link to a component in Figma (documentation link), perhaps this information could also be brought forward in the spec?

**Comment by nathanacurtis** [comment]
@twjeffery The challenge is enabling users (like you) to store metadata about a component that then gets displayed in such a manifest. The plugin is exceedingly dumb to what it can't read from a component today, which is limited to name, description and doc link. Those fields are wholly insufficient to auto-populate a status table. Will think more on this.

**Comment by twjeffery** [comment]
I appreciate the response. I will be interested to see what Figma will be releasing shortly at their conference for better developer collaboration. It would be worth considering and working from that as well. 

I love the plugin. Thanks for your work!

**Comment by nathanacurtis** [comment]
Appreciate the thinking! Thanks so much for chiming in, and hopefully we'll have that problem solved – Figma or plugin – sometime soon.
