### ISSUE TITLE
Error: Zero width node resizing 

### ISSUE THREAD

**Issue by hostmyname** [EightShapes/specs-plugin#89]
in resize: Expected "width" to have value >= 0.01

**Comment by nathanacurtis** [comment]
@hostmyname That's interesting. I recently implemented a fix to prevent failures when resizing across all instances where resizing is performed. Could you provide more details on your component? For example...
* Do you have layers with `0` width or height?
* What kinds of node is it: `FRAME`, `TEXT`, `POLYGON`, etc?
* Might you be able to share a view-only access of an example for me to inspect?

**Comment by nathanacurtis** [comment]
@hostmyname Hey there, just checking in. Do you have any further details you can provide about the issue, regarding my questions above? If I don't hear from you soon, I'll go ahead and close the issue.
