### ISSUE TITLE
Error: Zero width node resizing

### ISSUE THREAD

**Issue by Hejka-J** [EightShapes/specs-plugin#93]
### Description

I was using the Figma Plugin, and when I clicked on one of my desktop Frames (1920x1080) it continuously gives this error:
_in resize: Expected "width" to have value >= 0.01_

1. Opened Figma File
2. Clicked on my Frame
3. Clicked Plugins > EightShapes Spec
4. "Create Spec"
5. **Error**

### Screenshot
<img width="299" alt="Screenshot 2023-06-12 at 8 24 22 AM" src="https://github.com/EightShapes/specs-plugin/assets/107773796/02292e05-801d-4e62-87bd-6bb4c25ba664">

**Comment by nathanacurtis** [comment]
@Hejka-J Similar to issue #89... That's interesting. I recently implemented a fix to prevent failures when resizing across all instances where resizing is performed. Could you provide more details on your component? For example...
* Do you have layers with `0` width or height?
* What kinds of node is it: `FRAME`, `TEXT`, `POLYGON`, etc?
* Might you be able to share a view-only access of an example for me to inspect?

**Comment by nathanacurtis** [comment]
@Hejka-J Following up, would you be able to clarify and provide more details on your use case? If I don't hear from you in the days to come, I'll close the issue as resolved. Thanks for your interest :)
