### ISSUE TITLE
Plugin error (no details provided)

### ISSUE THREAD

**Issue by fernandacaroline** [EightShapes/specs-plugin#94]
### Description

{Describe the bug in a sentence}

### Steps to reproduce

{Add steps to reproduce the error}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
@fernandacaroline Would you be able to provide more details about the error you encountered, such as:
- Good: The error message displayed
- Better: A screenshot of the plugin's UI, Figma canvas showing broken outputs and/or the item you ran the plugin on
- Best: Access to a view-only version of a Figma file with the item that produced the error so I could inspect it

Anything you can provide will help. Thanks for your interest in the plugin :)

**Comment by nathanacurtis** [comment]
Closing due to lack of response. Happy to inspect more if reopened with more details. Cheers :)
