### ISSUE TITLE
Prop variants showing incorrectly configured alternatives

### ISSUE THREAD

**Issue by dolcevitt** [EightShapes/specs-plugin#95]
### Description 

Plugin did not fetch the property (text style and size) of an item, leaving a blank space. While the other items with the same properties were specified correctly.

### Screenshot

![image](https://github.com/EightShapes/specs-plugin/assets/137181473/92269da3-d4e8-43d0-893c-91238ac14019)

**Comment by nathanacurtis** [comment]
@dolcevitt The `width` and `height` attributes will only be shown when the layer's resizing is set to `Fixed`. If the resizing is set to `Hug` or `Fill`, the attribute won't be shown. Could this be what you ran into?

**Comment by tatianso** [comment]
@nathanacurtis The components were set up all the same way, they only have different heights. The properties do show correctly in the anatomy tho: 
![image](https://github.com/EightShapes/specs-plugin/assets/37113416/8ca23da8-49b1-4979-9447-983fa14f0421)

**Comment by dolcevitt** [comment]
[@nathanacurtis](https://github.com/nathanacurtis) The components were set up all the same way, they only have different heights. The properties do show correctly in the anatomy tho: 
![image](https://github.com/EightShapes/specs-plugin/assets/137181473/98d9256b-9fe9-4fde-82e3-e5c35fb13636)

**Comment by nathanacurtis** [comment]
@dolcevitt This is a `WontFix` issue, and the plugin is behaving as expected, actually.

The plugin compares layers based on matches of all these traits:
1. Matching layer name (including all parent layer names)
2. Matching layer type
3. Matching layer name+type sort order position

In your default variant, the layer is named `Selector outlined`, whereas the other two variants call the layer `Selector`. Therefore, the plugin thinks those layers are different and doesn't compare them, and thus doesn't show the difference in the Properties section (and thus, `Selector outlined`'s `height` is documented in Anatomy).
