### ISSUE TITLE
cannot read property 'getLocalVariableCollections' of undefined

### ISSUE THREAD

**Issue by dianamancia** [EightShapes/specs-plugin#99]
### Description

{I couldn't run the plugin with any of the sections, always got the error message I put on the title of this PR}

### Steps to reproduce

{Selected component, opened de plugin, unchecked the Anatomy and Properties sections, left the Layout section checked, clicked on Create Specs, the error message appeared}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}
<img width="451" alt="Screenshot 2023-06-22 at 19 20 46" src="https://github.com/EightShapes/specs-plugin/assets/121573019/429085b0-8f83-4db2-93e3-81623441dd01">

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
@dianamancia 
This means that Figma isn't even exposing the new variables API at all to the Specs plugin. Have you completely restarted Figma, to reload all it's new features fresh? If a restart doesn't solve your problem, I'd love to troubleshoot with you to reproduce it myself, ideally using a view-only file that includes the component you are running it on.

**Comment by nathanacurtis** [comment]
I've published a version 22 fix that "Checks for `figma.variables` when creating local variable collection".

Pro plugin features for custom spec styling and dark mode will be impaired until (presumably, upon restart) you have access to Figma's variables features.

**Comment by dianamancia** [comment]
I restarted Figma as you said and now it worked!!! Yaaay 🥳
Thank you so much, Nathan! Thank you for helping me with this issue and for
building this awesome plugin which saves a ton of time and makes my work so
much more efficient. You're awesome and very inspiring! Hope I can get to
meet you someday at a Config or something.
That's all of me fangirling haha have a nice weekend and thanks again!

**Comment by nathanacurtis** [comment]
Great glad it helped! Have a great weekend, and best to you :)
